name: Test & Publish Coverage

on:
  push:
    branches:
      - master
jobs:
  func-build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
      - run: pnpm install
      - name: Execute tests
        run: pnpm run test
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
